language: java

cache:
  directories:
  - "$HOME/.gradle"
  - '$HOME/.m2/repository'
  - '$HOME/.sonar/cache'
  
jobs:
  include:
  - stage: Build
    script: mvn package
  - stage: SonarQube
    script: mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar
      -Dsonar.host.url=https://sonarcloud.io -Dsonar.organization=fsantiag -Dsonar.login=$SONAR_TOKEN
  - stage: Release
    script: echo "Releasing to Github..."
    deploy:
      provider: releases
      api_key:
        secure: IoGF1AEE/6jkNMgpYHPmEghfMgFcy/sZWjO62lqkkpFImFdSIijrGR3rjNCWkBfkRVdXHfNpCpQNXBhKuE8NA0K8qZXy+ay8xFjCIGBdUxLNGIA2/CLqrAgteUH9b+PrwvOiAyR8xCz4KnjfV9m6XeXSPmPpTz+fYjhW7Tt5m2fMY2simppuCHI4yn0x2H4bWFNR5YNzUQTIvKfduiO7+i+k5LV8GgKIYaEweBRx4xxP7kX7CXXTRgvyyCMXNSCAqbE07Y4puBDg6lNSxn4NhcBD8bhxmW9VNBkT76NL543GsY+LVZlmzi+MyeV/k8Uke3v95bfRKpDmfGFxFNMFERNyPXNPPwUjobu66tYioXjeuzUY4tbY4suDL9+0d6B49nWjOnavMPSGMFf2Z43TOYLb4lmQQZkvEWUQX/5TDvgPbCYjlPhnZanb7+LDt44VMXb8GeVxT3j+ommUgk0ES6jLd41NHYqFl9LjxdWfMg4He378RyCZBjUGq3J+UAGtQqaPIzRhMwPoCVuscWKCQw7Jd2xjP7LQxaxSuaJTM5hRnS/yIGmJR/gw96V3mRUIOcokBYtfV/CDdk3yYjdtCLk78jbtWyr5Wxz6bhAjomrAdq2dsMHFHDwgNOvpT7on2S/ObNcUhg8odkyCvdreCg258vBWOUZosvUfCGG6ZiQ=
      file: target/sonar-clojure-plugin-1.0.0-SNAPSHOT.jar
      skip_cleanup: true
      on:
        tags: true
env:
  global:
    secure: SclOuSipO+/x21fADxux17AqdHNk+v/Fw4MDKWUBRO+OxJa0qHkMdUlwTDBYAADanraHtebUQz54gQdtm+Ovi9Yev7KCJ3Y+wWVhXrk4VJtLmyIsT8FMO10kF7IO8lpnm3EkM5kP1/KG7Q4knUUlDthyRZAvjWCJrwS+L3udrYovciypRNgWSkJTtsDMYRX2KA+e2+k/mwNpu59oFockEN7KJM8ArknOpkWqoop7xk9KQdapHkKcFA0nYAgPd3F7SWScdbk65+KjNZnaJh9tIijaQycDmvcFOsUCh/+GIT5VWsWOwoTnBHhxhyO8of9+YbsX480tI0OR4p+/JdN6xP+v+xNVkagiJoIddpVHWF4CoId1PILOayszJciUy+8iA6dv0tYkAehxSvNhJ1s7bkbTKGW/oyvJfvCJS7rwjamVASpSKux7dCy1D5+OxkkfSohZ3tUlqlRrQiE7oJgCtuKUBdyU7efMyLJT65zABumXZER9ABgdqmk7476UlQqMhVFCa7lZMzB0A5aY2ikFhg+NsWJJ8qvb9xR9TPmypVUlwaCPeE6nZkjQ7y/GSqs7gja6RJ7HX5TX8ucaTB6jmZpwJzNENTy47pJ58HAdGVgIH6Gdvu+4SFZNq2jh2DfDYgKI1+5K6Y46CzAtmmwKcOSqvZhflKy1lTOhUeEHAT8=
